apiVersion: v1
kind: Service
metadata:
  name: {{ include "flaskr.fullname" . }}
  labels:
    {{- include "flaskr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: flaskr-www
      protocol: TCP
  selector:
    {{- include "flaskr.selectorLabels" . | nindent 4 }}
